### ISSUE TITLE
[BUG] Reloading causes 404

### ISSUE THREAD

**Issue by rellis6** [Idleon-Companion/IdleonCompanion#167]
# Bug Report

**Description**

Reloading on any page causes a 404 error.

`Not Found
The requested URL was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.`

To fix I have to remove the trailing part of the URL and go back to just https://idleoncompanion.com/

---

**Details**

OS (e.g. Windows, iOS): Windows
Browser (e.g. Chrome, Safari): Chrome
Idleon Companion Version (see changelog): 0.3.0

**Comment by 3ICE** [comment]
Because the UI gets laggy when typing ( See #139 ) I am often forced to reload the page. Encountered the above problem just now.

Can't even bookmark https://idleoncompanion.com/ anymore as it redirects to https://idleoncompanion.com/characters immediately. And that's a 404 when not bookmarked fast enough.

Alternative fix, use # for breadcrumb URL fragments.
For example:
https://idleoncompanion.com/#tracker/statues
instead of
https://idleoncompanion.com/tracker/statues

JS can check URL fragment onload and navigate back to the correct page.

**Comment by adapap** [comment]
Thanks for reporting this! It is a server-side issue rather than an issue with the website. I passed this info along to our host, so we should be able to resolve this and fix builds in the process.

OOC @3ICE - You can change the URL that bookmarks link to by right-clicking them (on Chrome).

**Comment by adapap** [comment]
Update: This issue is fixed now! Please open a new issue if you still experience problems :)
